from enum import Enum

# ============== ENUMS ==============


class NavigationStatus(int, Enum):
    UNDER_WAY_USING_ENGINE = 0
    AT_ANCHOR = 1
    NOT_UNDER_COMMAND = 2
    RESTRICTED_MANOEUVRABILITY = 3
    CONSTRAINED_BY_DRAUGHT = 4
    MOORED = 5
    AGROUND = 6
    ENGAGED_IN_FISHING = 7
    UNDER_WAY_SAILING = 8
    RESERVED_HSC = 9
    RESERVED_WIG = 10
    RESERVED_11 = 11
    RESERVED_12 = 12
    RESERVED_13 = 13
    AIS_SART = 14
    NOT_DEFINED = 15


class ShipType(int, Enum):
    NOT_AVAILABLE = 0
    WING_IN_GROUND = 20
    WIG_HAZARDOUS_A = 21
    WIG_HAZARDOUS_B = 22
    WIG_HAZARDOUS_C = 23
    WIG_HAZARDOUS_D = 24
    FISHING = 30
    TOWING = 31
    TOWING_LARGE = 32
    DREDGING = 33
    DIVING_OPS = 34
    MILITARY_OPS = 35
    SAILING = 36
    PLEASURE_CRAFT = 37
    HSC = 40
    HSC_HAZARDOUS_A = 41
    HSC_HAZARDOUS_B = 42
    HSC_HAZARDOUS_C = 43
    HSC_HAZARDOUS_D = 44
    HSC_NO_INFO = 49
    PILOT_VESSEL = 50
    SAR_VESSEL = 51
    TUG = 52
    PORT_TENDER = 53
    ANTI_POLLUTION = 54
    LAW_ENFORCEMENT = 55
    MEDICAL_TRANSPORT = 58
    PASSENGER = 60
    PASSENGER_HAZARDOUS_A = 61
    PASSENGER_HAZARDOUS_B = 62
    PASSENGER_HAZARDOUS_C = 63
    PASSENGER_HAZARDOUS_D = 64
    PASSENGER_NO_INFO = 69
    CARGO = 70
    CARGO_HAZARDOUS_A = 71
    CARGO_HAZARDOUS_B = 72
    CARGO_HAZARDOUS_C = 73
    CARGO_HAZARDOUS_D = 74
    CARGO_NO_INFO = 79
    TANKER = 80
    TANKER_HAZARDOUS_A = 81
    TANKER_HAZARDOUS_B = 82
    TANKER_HAZARDOUS_C = 83
    TANKER_HAZARDOUS_D = 84
    TANKER_NO_INFO = 89
    OTHER = 90
    OTHER_HAZARDOUS_A = 91
    OTHER_HAZARDOUS_B = 92
    OTHER_HAZARDOUS_C = 93
    OTHER_HAZARDOUS_D = 94
    OTHER_NO_INFO = 99


class ManeuverIndicator(int, Enum):
    NOT_AVAILABLE = 0
    NO_SPECIAL_MANEUVER = 1
    SPECIAL_MANEUVER = 2


class PositionAccuracy(int, Enum):
    LOW = 0
    HIGH = 1


class EPFDType(int, Enum):
    UNDEFINED = 0
    GPS = 1
    GLONASS = 2
    GPS_GLONASS = 3
    LORAN_C = 4
    CHAYKA = 5
    INTEGRATED = 6
    SURVEYED = 7
    GALILEO = 8


class AidType(int, Enum):
    """Aid to Navigation types for Message 21"""

    DEFAULT = 0
    REFERENCE_POINT = 1
    RACON = 2
    FIXED_STRUCTURE = 3
    SPARE_4 = 4
    LIGHT_NO_SECTORS = 5
    LIGHT_WITH_SECTORS = 6
    LEADING_LIGHT_FRONT = 7
    LEADING_LIGHT_REAR = 8
    BEACON_CARDINAL_N = 9
    BEACON_CARDINAL_E = 10
    BEACON_CARDINAL_S = 11
    BEACON_CARDINAL_W = 12
    BEACON_PORT_HAND = 13
    BEACON_STARBOARD_HAND = 14
    BEACON_PREFERRED_CHANNEL_PORT = 15
    BEACON_PREFERRED_CHANNEL_STARBOARD = 16
    BEACON_ISOLATED_DANGER = 17
    BEACON_SAFE_WATER = 18
    BEACON_SPECIAL_MARK = 19
    BEACON_LIGHT_VESSEL = 20
    LANBY = 21
    BUOY_CARDINAL_N = 22
    BUOY_CARDINAL_E = 23
    BUOY_CARDINAL_S = 24
    BUOY_CARDINAL_W = 25
    BUOY_PORT_HAND = 26
    BUOY_STARBOARD_HAND = 27
    BUOY_PREFERRED_CHANNEL_PORT = 28
    BUOY_PREFERRED_CHANNEL_STARBOARD = 29
    BUOY_ISOLATED_DANGER = 30
    BUOY_SAFE_WATER = 31


